### ISSUE TITLE
Sass import problems

### ISSUE THREAD

**Issue by Difusio** [emlama/meteor-foundation5-sass#13]
I'm not really sure if this is a problem with this package, or my beginning knowledge of sass, delete the issue if it's the latter.

I've got a Meteor project with the following file structure:

.meteor
client
|- dashboard
|-- dashboard.scss
|- client.scss
My basic sass file is client.scss that resides in client folder.

If I define $flat-button in client.scss. Then I cannot use it in dashboard.css without adding `@import '../client';`. However when I do this in multiple files this causes duplicate entries in the unified css file. If I don't import it then Meteor reports errors due to not finding the variable.

**Comment by jadsonlourenco** [comment]
Yes, it's an organizational problem that you're doing it wrong. Not of this package.

Normally I do so:
- _variables.scss (all variables)
- _my-page.scss (my style for this page)
- _other-page.scss (my style for this page)
- app.scss (import all files here, by categories)

Then I import the "variables" file before the files of pages, so I will have a value only where I can use all of the following files, and will not be duplicated.

Tell me if you got it please.

**Comment by Difusio** [comment]
I get what you're saying, but doesn't this interfere with the automatic concatenating that the packages does?

**Comment by jadsonlourenco** [comment]
As well "interfere"?

I do not know how is your thought on this within Meteor, but I had this doubt from the first moment I used this package with Meteor, to compile SCSS.

I expected the traditional method, which would have a folder with SCSS or another folder (or single file) for compiled CSS, because with the "grunt" work that way.

But if weather is different, you do not have to worry about the final CSS, because it will be generated at the end of the project when you package your application to production with "meteor build", it will generate all your application in the format "NODE application" and SCSS styles (including Foundation) will be only one CSS file, single file.

At least that's how it works for me so far, and I suppose this is your question.

**Comment by emlama** [comment]
@Difusio, Meteor only concatenates CSS files and not SCSS files. If you setup your project as @jadsonlourenco suggested, then the SASS package will handle building a single `app.css` file that Meteor can include for your site.

If you are working with straight CSS, Meteor is great because it takes care of minifying and concatenating the files. In other frameworks, this is something that you would normally use Grunt or SASS for. If you're going to use SASS in Meteor you should bypass Meteor's management of CSS files and build a single CSS file as @jadsonlourenco suggested.

**Comment by Difusio** [comment]
Great, I've got a chance to try this out in 30 minutes. Thanks for helping, you can close down this issue if you like.

**Comment by jadsonlourenco** [comment]
Yes, I'm closing this. @Difusio I hope you get this working, good luck.
