### ISSUE TITLE
customize foundation components?

### ISSUE THREAD

**Issue by eshell** [emlama/meteor-foundation5-sass#18]
Hi, is it possible to customize included foundation components? I tried customizing the ".meteor/local/build/programs/.../scss/foundation.scss" to only include components I will use, but it appears to keep getting overwritten. 

Also, how would I exclude javascripts I won't use? I'm very new to meteor btw.

**Comment by jadsonlourenco** [comment]
To not load the js just remove this call on your HTML code **{{initFoundation}}** if you have.

To customize the components of SCSS, you can load like Foundation do: https://github.com/zurb/foundation/blob/master/scss/foundation.scss
This example you can see how load each component, but you will need change the location, if you want load each component do that:

```
// Foundation root folder
$foundation_root: ".meteor/local/build/programs/server/assets/packages/matthew_foundation5-sass/scss/";

// Load components
@import "#{$foundation_root}foundation/components/grid";
...
```

**Comment by eshell** [comment]
I just found an easier way to customize your package. I just create my own, copy your git repo into it, customize package.js to exclude whatever I dont want, then add my new package to meteor. 

EDIT:
ok.. not that easy. getting errors. i'll keep you posted =)

EDIT:
got it working. had to remove unused scss components from foundation.scss as well. although i could just modify package.js to remove foundation javascript files, keep the scss files, and just comment out foundation.scss instead of commenting out scss files twice.

either way, i got a custom build working, thanks =)

**Comment by jadsonlourenco** [comment]
I understand. But the disadvantage of using a custom package is that you will miss the updates, imagine if you do it with other packages used in your project. Another disadvantage is you don't understand how Meteor work with packages, because in my opinion have packages is to facilitate our work, if I want to add something that will be customized for my project then use as part of the project files (usually in the  "lib" folder).

But I'm glad you could make it work, but as I have shown in the previous example, Foundation is the same, this package only helps to not take the trouble to download and add the Foundation files manually, and you can customize as needed. :D
